### ISSUE TITLE
[buildpkg] Where does signpkg get the gpg key?

### ISSUE THREAD

**Issue by ryanvade** [manjaro/manjaro-tools#107]
When you use the -s flag with buildpkg, where is signpkg getting the gpg key? Is it possible to load the calling users keys? Or do you have to copy then to the chroot?

**Comment by udeved** [comment]
Local user key is used.

**Comment by ryanvade** [comment]
How so? When I try to use the sign option it attempts to use an empty key.

**Comment by udeved** [comment]
You need to set your key in /etc/makepkg.conf

https://www.archlinux.org/pacman/makepkg.conf.5.html

**Comment by ryanvade** [comment]
Very well then.  Could this be made a bit more clear in the readme?

**Comment by udeved** [comment]
From my pov, nope, because makepkg is essential to arch based systems, and its documented on the wiki.
Secondly, since makepkg is not part of manjaro-tools, it is assumed the user is familiar with the basics.
Keep in mind, these are development tools, which do not necessarily target average manjaro user.

**Comment by ryanvade** [comment]
Okay.  I just don't think it is clear that the host systems makepkg config is being used since the actual building is in a chroot. My first thought would be it copies the key over to the chroot then builds.  Doesn't matter though I understand now.
