### ISSUE TITLE
[buildpkg] option to use custom mirrorlist or host mirrorlist

### ISSUE THREAD

**Issue by manjaro** [manjaro/manjaro-tools#27]
As I have for example direct access to repo.manjaro.org I like also to use that mirror on my pkg-chroots. This way I can be sure to use the latest packages currently present and don't have to wait for other mirrors to sync.

**Comment by udeved** [comment]
I propose we release a stable 0.9.5.7 first.

I would implement your request in 0.9.6 if that's ok. But lets first squash as many bugs and glitches as possible before we do new features. Its been in my mind for some time to have a custom mirror.

**Comment by manjaro** [comment]
Sure, just go for it. Current version is fine to be released as **0.9.5.7**.

**Comment by udeved** [comment]
Where should the custom mirror be located in filesystem? 
/usr/share/manjaro-tools or a custom location which can be configured?

**Comment by manjaro** [comment]
Just load it into **/usr/share/manjaro-tools** by defining it. For example I point to **/etc/pacman.d/mirrorlist** you can copy that over to **/usr/share/manjaro-tools**. Else any other path as source would be fine. I'm open for your ideas.

**Comment by udeved** [comment]
The thing is, I had the idea to introduce a manjaro-tools folder in $HOME, which iso profiles could symlink their custom pacman.conf files for example.
This would remove current location $HOME/.config/manjaro-tools.conf, and would shift it to its user dir.

This folder would also contain sets, and could also host a custom mirror.
We kind of centralize overrides in $HOME/.manjaro-tools for /etc/manjaro-tools and /usr/share/manjaro-tools. Otherwise data overriding /usr/share would go in $HOME/.local I think.

**Comment by udeved** [comment]
I assume the custom mirror should adapt to branch? Would be cool I think.

**Comment by manjaro** [comment]
Yes, I'm with you with this ...

**Comment by udeved** [comment]
Well, I restored the old behaviour I switched off for buildpkg, due to the umount error in buildiso.

It now created by default a netzspielplatz mirror of the right branch.

If we do a manjaro-tools folder is independent of this, but I think this is what you basically wanted.

**Comment by udeved** [comment]
The only thing I haven't tested yet if pacman -Sddp community/manjaro-tools return netzspielplatz mirror if you have a non German pacman-mirrors.conf set.

If it doesn't, I will implement as requested an option to pass a mirror via parameter or manjaro-tools.conf
