### ISSUE TITLE
[conf] move pacman-mirrors?

### ISSUE THREAD

**Issue by udeved** [manjaro/manjaro-tools#94]
I saw the recent pacman-mirrors update and it got me thinking if we should make manjaro-tools use install location of pacman-mirrors or other conf files such as makepkg? 
Like the idea to have a shared location for these files so we don't need to sync them if changed, present without manjaro-tools installed? Say pacman-mirrors.conf for the 3 branches gets installed in /usr/share/pacman-mirrors/*, pacman.conf and makepkg conf similar.

**Comment by Kirek** [comment]
I'm not sure that I get what you mean, don't manjaro-tools ships default .conf files for makepkg, pacman and pacman-mirrors?

**Comment by udeved** [comment]
Yep, I just just wondered if you should provide these files with a manjaro standard package already? Be it pacman, pacman-mirrorlist whatever. :)

**Comment by Kirek** [comment]
Ok, now I understand.
I don't think we should do that because for example if we ship the "pacman-*.conf files in pacman package, we would be providing 4 files in the pacman package that pacman doesn't use for anything, they are only make sense when manjaro-tools is installed. Same for makepkg-*.conf and pacman-mirrors-*.conf
I don't think we gain anything with this.

**Comment by udeved** [comment]
I think, if we did something like this, eg providing conf or a util-msg.sh, manjaro-system would be the package for it.
Anyway, just a thought, its also fine as it is. :)

**Comment by philmmanjaro** [comment]
Well, I think we don't have the need to change it now. If some would be gained out of it, well then yes ...
